"""empty message

Revision ID: 3e27515aa66e
Revises: 211fcb5a948d
Create Date: 2023-04-20 16:45:16.192364

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3e27515aa66e"
down_revision = "211fcb5a948d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("params", sa.Column("message", sa.BIGINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("params", "message")
    # ### end Alembic commands ###
