version: '3'

services:

  postgres_optimizer:
    image: postgres:13
    profiles:
      - optimizer
    environment:
      POSTGRES_USER: ${OPTIMIZER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${OPTIMIZER_POSTGRES_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: ${OPTIMIZER_POSTGRES_DATABASE}
    volumes:
      - postgres-optimizer-db-volume:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    restart: always

  optimizer:
    image: optimizer
    container_name: optimizer
    profiles:
      - optimizer
    build:
      context: .
      dockerfile: docker/optimizer/Dockerfile
    depends_on:
      - postgres_optimizer
    env_file:
      - .env
    restart: always
    ports:
      - "8081:80"
    volumes:
      - "./app/optimizer_api:/app/optimizer_api"

  optimizer_frontend:
    image: optimizer_frontend
    container_name: optimizer_frontend
    profiles:
      - optimizer
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    depends_on:
      - optimizer
    restart: always
    ports:
      - "8082:80"
    volumes:
      - "./app/frontend:/usr/share/nginx/html"

  classifier_serving:
    image: tensorflow/serving
    container_name: classifier_serving
    profiles:
      - ai
    restart: always
    environment:
      - MODEL_NAME=classifier
    ports:
      - "8501:8501"
    volumes:
      - "./models/classifier:/models/classifier"

  postgres_ai:
    image: postgres:13
    profiles:
      - ai
    environment:
      POSTGRES_USER: ${OPTIMIZER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${OPTIMIZER_POSTGRES_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: ${OPTIMIZER_POSTGRES_DATABASE}
    volumes:
      - postgres-ai-db-volume:/var/lib/postgresql/data
    ports:
      - "15433:5432"
    restart: always

volumes:
  postgres-optimizer-db-volume:
  postgres-ai-db-volume:
