"""empty message

Revision ID: 8a82cd444fdd
Revises: 9132632aa343
Create Date: 2023-04-26 11:09:23.502335

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8a82cd444fdd"
down_revision = "9132632aa343"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "params_history", sa.Column("current_param", sa.Integer(), nullable=True)
    )
    op.add_column(
        "params_history", sa.Column("batch_size", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("params_history", "batch_size")
    op.drop_column("params_history", "current_param")
    # ### end Alembic commands ###
