"""empty message

Revision ID: 9132632aa343
Revises: b9f5bc743004
Create Date: 2023-04-20 16:45:34.884005

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9132632aa343"
down_revision = "b9f5bc743004"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("params_history", sa.Column("message", sa.BIGINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("params_history", "message")
    # ### end Alembic commands ###
